import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGooglePlusCircle,
  AiFillGooglePlusSquare,
  AiFillGoogleSquare,
  AiFillGoogleCircle,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import dhairya from "../public/dhairya2.webp";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

import youtube from "../public/youtube.png";
import movie from "../public/movie.png";
import react from "../public/react.png";
import redux from "../public/redux.png";
import emoji from "../public/emoji.png";
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Dhairya Parikh Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white sticky top-0 z-100">
            <h1 className="font-burtons text-xl">developedbyDhairya</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  target="_blank"
                  href="https://drive.google.com/file/d/1k0-zsOjs0HvxFH6Cfif1TUTIGRSllnyy/view?usp=sharing "
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Dhairya Parikh
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Software Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              As a junior software engineer, I am an enthusiastic young coder
              who loves to code and is passionate about solving problems. I have
              a natural curiosity and enjoy taking on new challenges in the
              world of software development.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a target="_blank" href="https://github.com/dhairyaaaaa14">
                <AiFillGithub />
              </a>
              <a target="_blank" href="https://twitter.com/Dhairya74432744">
                <AiFillTwitterCircle />
              </a>
              <a
                target="_blank"
                href="https://www.linkedin.com/in/dhairya-parikh15/"
              >
                <AiFillLinkedin />
              </a>
              <a href="mailto: dhaiyawork15@gmail.com">
                {" "}
                <AiFillGoogleCircle />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image alt="" src={dhairya} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">
              Web Development Projects
            </h3>

            <p className="text-md py-2 leading-6 text-gray-800 dark:text-gray-200">
              In each of these projects, I demonstrated strong proficiency in
              web development technologies and tools, as well as the ability to
              work independently or as part of a team. I also have experience in
              <span className="text-teal-500"> version control</span> and
              <span className="text-teal-500"> agile methodology</span> .
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1 scale-90 hover:scale-100 ease-in duration-500">
              <Image
              alt=''
                className="mx-auto"
                src={youtube}
                width={150}
                height={120}
              />
              <a
                href="https://youtube-clone-rho-one.vercel.app/"
                target="_blank"
              >
                <h3 className="text-lg font-medium pt-6 pb-2 text-black">
                  Youtube Clone
                </h3>
              </a>
              <p className="py-2 text-sky-700">
                The YouTube clone project using React is a web application that
                emulates the functionality and design of the popular
                video-sharing platform YouTube.
              </p>
              <h4 className="py-4 text-teal-600">Technologies used</h4>
              <p className="text-gray-800 py-1">React JS</p>
              <Image alt='' className="mx-auto" src={react} height={50} />
              <p className="text-gray-800 py-1">Redux</p>
              <Image alt='' className="mx-auto" src={redux} height={50} />
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1 scale-90 hover:scale-100 ease-in duration-500">
              <Image
              alt=''
                className="mx-auto mt-5"
                src={movie}
                width={100}
                height={100}
              />
              <a
                href="https://movie-app-dhairya-parikh.vercel.app/"
                target="_blank"
              >
                <h3 className="text-lg font-medium pt-8 pb-5 text-black ">
                  Movie App
                </h3>
              </a>
              <p className="py-2  text-sky-700">
                React Movie App is a web application built using React and the
                Open Movie Database (OMDb) API.The app allows users to search
                for their favorite movies and TV shows.
              </p>
              <h4 className="py-4 text-teal-600">Technologies used</h4>
              <Image alt='' className="mx-auto" src={react} height={50} />
              <p className="text-gray-800 py-1">React JS</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1 scale-90 hover:scale-100 ease-in duration-500">
              <Image alt='' className="mx-auto" src={emoji} width={100} height={100} />
              <a href="https://emoji-dictionary-xi.vercel.app/" target="_blank">
                <h3 className="text-lg font-medium pt-8 pb-2 text-black ">
                  Emoji Pedia
                </h3>
              </a>
              <p className="py-2  text-sky-700">
                Emoji Pedia is a fun and interactive mobile application that
                allows users to search, discover, and learn about various emojis
                and their meanings.Users can search for emojis by keyword,
                category, or simply by browsing through the vast library of
                emojis available
              </p>
              <h4 className="py-4 text-teal-600">Technologies used</h4>
              <p className="text-gray-800 py-1">React JS</p>
              <Image alt="" className="mx-auto" src={react} height={50} />
            </div>
          </div>
        </section>
        
      </main>
    </div>
  );
}




// import Image from 'next/image'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export default function Home() {
//   return (
//     <main
//       className={`flex min-h-screen flex-col items-center justify-between p-24 ${inter.className}`}
//     >
//       <div className="z-10 w-full max-w-5xl items-center justify-between font-mono text-sm lg:flex">
//         <p className="fixed left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto  lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30">
//           Get started by editing&nbsp;
//           <code className="font-mono font-bold">pages/index.tsx</code>
//         </p>
//         <div className="fixed bottom-0 left-0 flex h-48 w-full items-end justify-center bg-gradient-to-t from-white via-white dark:from-black dark:via-black lg:static lg:h-auto lg:w-auto lg:bg-none">
//           <a
//             className="pointer-events-none flex place-items-center gap-2 p-8 lg:pointer-events-auto lg:p-0"
//             href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template-tw&utm_campaign=create-next-app"
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             By{' '}
//             <Image
//               src="/vercel.svg"
//               alt="Vercel Logo"
//               className="dark:invert"
//               width={100}
//               height={24}
//               priority
//             />
//           </a>
//         </div>
//       </div>

//       <div className="relative flex place-items-center before:absolute before:h-[300px] before:w-[480px] before:-translate-x-1/2 before:rounded-full before:bg-gradient-radial before:from-white before:to-transparent before:blur-2xl before:content-[''] after:absolute after:-z-20 after:h-[180px] after:w-[240px] after:translate-x-1/3 after:bg-gradient-conic after:from-sky-200 after:via-blue-200 after:blur-2xl after:content-[''] before:dark:bg-gradient-to-br before:dark:from-transparent before:dark:to-blue-700/10 after:dark:from-sky-900 after:dark:via-[#0141ff]/40 before:lg:h-[360px]">
//         <Image
//           className="relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert"
//           src="/next.svg"
//           alt="Next.js Logo"
//           width={180}
//           height={37}
//           priority
//         />
//       </div>

//       <div className="mb-32 grid text-center lg:mb-0 lg:grid-cols-4 lg:text-left">
//         <a
//           href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template-tw&utm_campaign=create-next-app"
//           className="group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           <h2 className={`mb-3 text-2xl font-semibold`}>
//             Docs{' '}
//             <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">
//               -&gt;
//             </span>
//           </h2>
//           <p className={`m-0 max-w-[30ch] text-sm opacity-50`}>
//             Find in-depth information about Next.js features and API.
//           </p>
//         </a>

//         <a
//           href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template-tw&utm_campaign=create-next-app"
//           className="group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           <h2 className={`mb-3 text-2xl font-semibold`}>
//             Learn{' '}
//             <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">
//               -&gt;
//             </span>
//           </h2>
//           <p className={`m-0 max-w-[30ch] text-sm opacity-50`}>
//             Learn about Next.js in an interactive course with&nbsp;quizzes!
//           </p>
//         </a>

//         <a
//           href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template-tw&utm_campaign=create-next-app"
//           className="group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           <h2 className={`mb-3 text-2xl font-semibold`}>
//             Templates{' '}
//             <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">
//               -&gt;
//             </span>
//           </h2>
//           <p className={`m-0 max-w-[30ch] text-sm opacity-50`}>
//             Discover and deploy boilerplate example Next.js&nbsp;projects.
//           </p>
//         </a>

//         <a
//           href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template-tw&utm_campaign=create-next-app"
//           className="group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           <h2 className={`mb-3 text-2xl font-semibold`}>
//             Deploy{' '}
//             <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">
//               -&gt;
//             </span>
//           </h2>
//           <p className={`m-0 max-w-[30ch] text-sm opacity-50`}>
//             Instantly deploy your Next.js site to a shareable URL with Vercel.
//           </p>
//         </a>
//       </div>
//     </main>
//   )
// }
