import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGooglePlusCircle,
  AiFillGooglePlusSquare,
  AiFillGoogleSquare,
  AiFillGoogleCircle,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import dhairya from "../public/dhairya2.webp";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

import youtube from "../public/youtube.png";
import movie from "../public/movie.png";
import react from "../public/react.png";
import redux from "../public/redux.png";
import emoji from "../public/emoji.png";
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Dhairya Parikh Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white sticky top-0 z-100">
            <h1 className="font-burtons text-xl">developedbyDhairya</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  target="_blank"
                  href="https://drive.google.com/file/d/1k0-zsOjs0HvxFH6Cfif1TUTIGRSllnyy/view?usp=sharing "
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Dhairya Parikh
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Software Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              As a junior software engineer, I am an enthusiastic young coder
              who loves to code and is passionate about solving problems. I have
              a natural curiosity and enjoy taking on new challenges in the
              world of software development.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a target="_blank" href="https://github.com/dhairyaaaaa14">
                <AiFillGithub />
              </a>
              <a target="_blank" href="https://twitter.com/Dhairya74432744">
                <AiFillTwitterCircle />
              </a>
              <a
                target="_blank"
                href="https://www.linkedin.com/in/dhairya-parikh15/"
              >
                <AiFillLinkedin />
              </a>
              <a href="mailto: dhaiyawork15@gmail.com">
                {" "}
                <AiFillGoogleCircle />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={dhairya} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">
              Web Development Projects
            </h3>

            <p className="text-md py-2 leading-6 text-gray-800 dark:text-gray-200">
              In each of these projects, I demonstrated strong proficiency in
              web development technologies and tools, as well as the ability to
              work independently or as part of a team. I also have experience in
              <span className="text-teal-500"> version control</span> and
              <span className="text-teal-500"> agile methodology</span> .
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1 scale-90 hover:scale-100 ease-in duration-500">
              <Image
                className="mx-auto"
                src={youtube}
                width={150}
                height={120}
              />
              <a
                href="https://youtube-clone-rho-one.vercel.app/"
                target="_blank"
              >
                <h3 className="text-lg font-medium pt-6 pb-2 text-black">
                  Youtube Clone
                </h3>
              </a>
              <p className="py-2 text-sky-700">
                The YouTube clone project using React is a web application that
                emulates the functionality and design of the popular
                video-sharing platform YouTube.
              </p>
              <h4 className="py-4 text-teal-600">Technologies used</h4>
              <p className="text-gray-800 py-1">React JS</p>
              <Image className="mx-auto" src={react} height={50} />
              <p className="text-gray-800 py-1">Redux</p>
              <Image className="mx-auto" src={redux} height={50} />
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1 scale-90 hover:scale-100 ease-in duration-500">
              <Image
                className="mx-auto mt-5"
                src={movie}
                width={100}
                height={100}
              />
              <a
                href="https://movie-app-dhairya-parikh.vercel.app/"
                target="_blank"
              >
                <h3 className="text-lg font-medium pt-8 pb-5 text-black ">
                  Movie App
                </h3>
              </a>
              <p className="py-2  text-sky-700">
                React Movie App is a web application built using React and the
                Open Movie Database (OMDb) API.The app allows users to search
                for their favorite movies and TV shows.
              </p>
              <h4 className="py-4 text-teal-600">Technologies used</h4>
              <Image className="mx-auto" src={react} height={50} />
              <p className="text-gray-800 py-1">React JS</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1 scale-90 hover:scale-100 ease-in duration-500">
              <Image className="mx-auto" src={emoji} width={100} height={100} />
              <a href="https://emoji-dictionary-xi.vercel.app/" target="_blank">
                <h3 className="text-lg font-medium pt-8 pb-2 text-black ">
                  Emoji Pedia
                </h3>
              </a>
              <p className="py-2  text-sky-700">
                Emoji Pedia is a fun and interactive mobile application that
                allows users to search, discover, and learn about various emojis
                and their meanings.Users can search for emojis by keyword,
                category, or simply by browsing through the vast library of
                emojis available
              </p>
              <h4 className="py-4 text-teal-600">Technologies used</h4>
              <p className="text-gray-800 py-1">React JS</p>
              <Image className="mx-auto" src={react} height={50} />
            </div>
          </div>
        </section>
        {/* <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section> */}
      </main>
    </div>
  );
}
